.TH evince\-thumbnailer 1 2007\-01\-15
.SH NAME
evince\-thumbnailer \- create png thumbnails from PostScript and PDF documents
.SH SYNOPSIS
\fBevince\-thumbnailer\fR [\-s \fBsize\fR] \fBinput\fR \fBoutput\fR
.SH DESCRIPTION
evince\-thumbnailer is a GNOME program to
create thumbnails from PostScript (PS), Portable Document Format
(PDF), DjVu and DVI files.
.SH OPTIONS
evince obeys all normal GNOME and GTK+
command line options. The only option \-s \fIsize
\fRmakes it possible to choose the vertical size
of the created thumbnail.
.SH "SEE ALSO"
\fBevince\fR(1),
\fBgnome\-options\fR(7),
\fBgtk\-options\fR(7).
.PP
http://www.gnome.org/projects/evince/
