.TH evince\-previewer 1 2015\-07\-28
.SH NAME
evince\-previewer \- show a printing preview of PostScript and PDF documents
.SH SYNOPSIS
\fBevince\-previewer\fR [options] \fBinput\fR
.SH DESCRIPTION
evince\-previewer is a GNOME program to
show a printing preview from PostScript (PS), Portable Document Format
(PDF), DjVu and DVI files.

This program is not meant to be called by end-users.
.SH OPTIONS
evince\-previewer obeys all normal GNOME and GTK+ command line options.
The application options are
.TP
\fB\-u, \-\-unlink\-tempfile\fR
Delete the temporary file
.TP
\fB\-p, \-\-print-settings=FILE\fR
Print settings file
.SH "SEE ALSO"
\fBevince\fR(1),
\fBgnome\-options\fR(7),
\fBgtk\-options\fR(7).
.PP
https://wiki.gnome.org/Apps/Evince
