.TH evince 1 "19 Jun 2011" "Evince maintainers"
.SH NAME
\fBevince\fP \- document viewer

The Evince document viewer application for the GNOME desktop environment

.SH SYNTAX
.B evince
.RI [--help]
.RI [--page-label=PAGE\ |
.RI --page-index=NUMBER\ |
.RI --named-dest=DEST]
.RI [--fullscreen]
.RI [--presentation]
.RI [--preview]
.RI [--find=STRING]
.RI [filename(s)...\ OR\ uri(s)...]
.SH DESCRIPTION
.B evince

Evince is a document viewer capable of displaying multiple and single
page document formats like PDF and Postscript.  For more general
information about Evince please visit our website at
https://gitlab.gnome.org/GNOME/evince

.LP
.SH OPTIONS

.TP
\fB\-?, \-h, \-\-help\fR
Prints the command line options.
.TP
\fB\-p, \-\-page\-label=PAGE\fR
Open the document on the page with the specified page label (or page number).
.TP
\fB\-i, \-\-page\-index=NUMBER\fR
Open the document on the page with the specified page index (this is the exact page number, not a page label).
.TP
\fB\-n, \-\-named\-dest=DEST\fR
Open the document on the specified named destination.
.TP
\fB\-f, \-\-fullscreen\fR
Run evince in fullscreen mode.
.TP
\fB\-s, \-\-presentation\fR
Run evince in presentation mode.
.TP
\fB\-l, \-\-find=string\fR
You can pass a word or phrase here. If it exists, evince will display
the document and the first match.
.TP
\fBfilename(s)... OR uri(s)...\fR
Specifies the file to open when Evince starts. If this is not
specified, Evince will open with the Recent Files view. Multiple files can be loaded
if they are separated by spaces.  Evince also supports handling of
remote files.  For example, you can pass the location on the web or load
a file from a FTP server, like "ftp://adobe.com/sample.pdf". File uri's are
also allowed eg. "file:///home/user/Documents/sample.pdf"

We partially support the Adobe PDF open parameters, specifically the
"page" and "nameddest" parameters, which are similar to our \-\-named\-dest
and \-\-page\-label options respectively. Some examples below:
  - file:///home/user/Documents/sample.pdf#page=12
  - https://arxiv.org/pdf/2310.01425#nameddest=section.3
  - sample.pdf#Page=5
  - sample.pdf#NamedDest=Chapter4

  Tip: you can obtain the list of all named destinations in a pdf file
       with the "pdfinfo -dests" command of poppler-utils package.

Evince also treats a numeric solely parameter as the "page" number, eg:
  - sample.pdf#5
  - https://arxiv.org/pdf/2310.01425#7

.SH Print preview options
These options are primarily intended for use with the GTK+ print
preview function. For more information about these options see
https://docs.gtk.org/gtk3/property.Settings.gtk-print-preview-command.html
.TP
\fB\-w, \-\-preview\fR
Run evince as a previewer.
.TP
\fB\-\-unlink\-temp\-file\fR
If evince is run in preview mode, this will unlink the temporary file
created by GTK+.
.TP
\fB\-\-print\-settings %s %f
This sends the full path of the PDF file, f, and the settings of the
print dialog, s, to evince.

.SH BUGS
If you find a bug, please report it at https://gitlab.gnome.org/GNOME/evince/issues.
